name: Build and deploy .NET Core application to Web App hqdqhengdtz4w-website
on:
  push:
    branches:
    - master
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: pending-website
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
  RG: rg_WDFW_PSCR_Daily
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Run Script
      run: dotnet-script ./HttpClient.csx

            
