name: Build and deploy .NET Core application to Web App hqdqhengdtz4w-website
on:
  push:
    branches:
    - master
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: hqdqhengdtz4w-website
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
  RG: rrg_WDFW_PSCR_Daily
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
    - uses: actions/checkout@v2
    - name: deploy Plan and Web Site
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RG }}
        template: ./deploy-WDFW_PSCR_Daily.bicep
        failOnStdErr: false        
    - name: deploy fetch test secret from key vault
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RG }}
        template: ./deploy-WDFW_PSCR_Daily.bicep
        parameters: '@deploy-WDFW_PSCR_Daily-parameters.json'
        failOnStdErr: false        

            
